services:
  - type: web
    name: kaith-bot
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: "python main.py"
    autoDeploy: true
